### ISSUE TITLE
Failed setup: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

### ISSUE THREAD

**Issue by risimmons** [skodaconnect/homeassistant-myskoda#226] opened 2024-11-09 10:27 UTC
**Describe the bug**
Just setting this up for the first time today.  On install after enter username/password it spent a while showing "initialising" and then the following is shown in Home assistant

Failed setup, will retry: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

The car is an Octavia iV plug in hybrid (2021)

**Is this working in MySkoda app?***
The car is listed/working in the MySkoda app.  I'm not seeing any data in "Driving data" on the app - I think that's why it's crashing; the data for that is coming back empty and that isn't handled

**Latest working release**
N/A

**Debug logs**
2024-11-09 10:07:07.130 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"vehicleType":"HYBRID","detailedStatistics":[{"date":"2024-11-04"},{"date":"2024-11-05"},{"date":"2024-11-06"},{"date":"2024-11-07"},{"date":"2024-11-08"},{"date":"2024-11-09"},{"date":"2024-11-10"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance
2024-11-09 10:07:07.134 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version (when running Core or Supervised) [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**

**Comment by risimmons** [comment] 2024-11-09 15:19
Just to note - I'm no longer seeing this issue.  I had only just paid the skoda subscription, so there was no drive data.  After going for a drive today the MySkoda app now shows some drive data and the integration doesn't crash.  I wouldn't call this fixed though.

**Comment by dvx76** [comment] 2024-11-09 15:22
Duplicate of #219

**Closed by dvx76** 2024-11-09 15:22 UTC
Labels: bug
