### ISSUE TITLE
"Switches" for parking heater and door locks

### ISSUE THREAD

**Issue by tiefflieger666** [skodaconnect/homeassistant-myskoda#214] opened 2024-11-08 10:40 UTC
First, thanks for the effort to bring the "new" MySkoda into HomeAssistant.

I'm own a Skoda Karoq 2021 - diesel engine with a parking heater and was using the old "Skoda connect" and created some nice automations.

Therefore the question if you plan or if it's even possible to implement the "switches"  avaliable in the old skoda_connect intergration (see screenshot) below.

Same question for the Combustion range, "moving" sensor etc

best regards

![slika](https://github.com/user-attachments/assets/2ef3af1b-2d03-4d8a-b09e-a202a5e75b40)

**Comment by WebSpider** [comment] 2024-11-08 11:16
Duplicate of #164

**Closed as completed** 2024-11-08 12:17 UTC
Labels: duplicate
