### ISSUE TITLE
Error when trying to activate myskoda integration

### ISSUE THREAD

**Issue by clasmayer** [skodaconnect/homeassistant-myskoda#210] opened 2024-11-08 09:01 UTC
Thank you for doing this !

Trying to add my car results in error, from the log.

Logger: myskoda.rest_api
Källa: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Inträffade först: 09:42:14 (2 händelser)
Senast loggade: 09:43:56

Failed to deserialize data: {"vehicles":[{"vin":"TMBLJ9NE9J0287858","name":"Octavia","licensePlate":"ABC123","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"5E5S0Z","title":"Škoda Octavia Combi","renders":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/G0G0c--rPUlVRzNX-rmhk5EWTgyIvcp-JvGFC-NEI5hTWq1sZxpKdbOC9jz8-31Fr9YBVws5oiH8MKOfznAJv-PKi4mA9UckyLze5g2o.ZtuG-B-19201080dayvext_side1080.png?v=638666511327408244","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5e5b29180112/G0G0c--rPUlVRzNX-rmhk5EWTgyIvcp-JvGFC-NEI5hTWq1sZxpKdbOC9jz8-31Fr9YBVws5oiH8MKOfznAJv-PKi4mA9UckyLze5g2o.ZtuG-B-700390dayvext_front1080.png?v=637859735740000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/G0G0c--rPUlVRzNX-rmhk5EWTgyIvcp-JvGFC-NEI5hTWq1sZxpKdbOC9jz8-31Fr9YBVws5oiH8MKOfznAJv-PKi4mA9UckyLze5g2o.ZtuG-B-19201080dayvext_side1080.png?v=638666511327408244","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {TMBLJ9NE9J0287858} failed with message {404 Not Found from GET http://render-service/api/v1/renders/TMBLJ9NE9J0287858}"}]}
Traceback (most recent call last):
  File "<string>", line 11, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'MISSING_RENDER' is not a valid GarageErrorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type GarageErrorType in GarageError has invalid value 'MISSING_RENDER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "errors" of type Optional[list[GarageError]] in Garage has invalid value [{'type': 'MISSING_RENDER', 'description': 'Getting render of view point {garage_l} for vehicle VIN {TMBLJ9NE9J0287858} failed with message {404 Not Found from GET http://render-service/api/v1/renders/TMBLJ9NE9J0287858}'}]

**Comment by WebSpider** [comment] 2024-11-08 09:44
Duplicate of #190

**Closed** 2024-11-08 09:45 UTC
Labels: bug, duplicate
