### ISSUE TITLE
v1.4.1 - Failed Setup

### ISSUE THREAD

**Issue by TimMeadows** [skodaconnect/homeassistant-myskoda#35] opened 2024-09-26 06:25 UTC
Hi, 

After I add the integration, I get a failed setup message, and this in the log. 

I've just started looking at the integration, and never had it work so far... 

Thanks for everything you are doing. 

```
Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 15, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'INITIALLY_DISABLED' is not a valid CapabilityStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/site-packages/myskoda/models/info.py", line 106, in drop_unknown_capabilities
    return [Capability.from_dict(c) for c in value if c["id"] in CapabilityId]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "statuses" of type list[CapabilityStatus] in Capability has invalid value ['INITIALLY_DISABLED']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 30, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "capabilities" of type list[Capability] in Capabilities has invalid value [{'id': 'AUTOMATION', 'statuses': []}, {'id': 'BATTERY_CHARGING_CARE', 'statuses': []}, {'id': 'BATTERY_SUPPORT', 'statuses': []}, {'id': 'CHARGING_PROFILES', 'statuses': []}, {'id': 'CHARGING_STATIONS', 'statuses': []}, {'id': 'DEALER_APPOINTMENT', 'statuses': ['INITIALLY_DISABLED']}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'MAP_UPDATE', 'statuses': []}, {'id': 'MEASUREMENTS', 'statuses': []}, {'id': 'PARKING_INFORMATION', 'statuses': []}, {'id': 'PARKING_POSITION', 'statuses': []}, {'id': 'PLUG_AND_CHARGE', 'statuses': []}, {'id': 'POI_SEARCH', 'statuses': []}, {'id': 'ROADSIDE_ASSISTANT', 'statuses': []}, {'id': 'ROUTING', 'statuses': []}, {'id': 'STATE', 'statuses': []}, {'id': 'TRAFFIC_INFORMATION', 'statuses': []}, {'id': 'VEHICLE_HEALTH_INSPECTION', 'statuses': []}, {'id': 'WARNING_LIGHTS', 'statuses': []}, {'id': 'WEB_RADIO', 'statuses': []}, {'id': 'AIR_CONDITIONING_TIMERS', 'statuses': []}, {'id': 'LOYALTY_PROGRAM', 'statuses': []}, {'id': 'AIR_CONDITIONING_SMART_SETTINGS', 'statuses': []}, {'id': 'POWERPASS_TARIFFS', 'statuses': []}, {'id': 'AIR_CONDITIONING_SAVE_AND_ACTIVATE', 'statuses': []}, {'id': 'CUBIC', 'statuses': []}, {'id': 'ROUTE_PLANNING_5_CHARGERS', 'statuses': []}, {'id': 'SUBSCRIPTIONS', 'statuses': []}, {'id': 'DESTINATIONS', 'statuses': []}, {'id': 'CHARGING_MEB', 'statuses': []}, {'id': 'VEHICLE_SERVICES_BACKUPS', 'statuses': []}, {'id': 'EV_ROUTE_PLANNING', 'statuses': []}, {'id': 'CHARGE_MODE_SELECTION', 'statuses': []}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'VEHICLE_HEALTH_WARNINGS', 'statuses': []}, {'id': 'PAY_TO_PARK', 'statuses': []}, {'id': 'ONLINE_SPEECH_GPS', 'statuses': []}, {'id': 'GUEST_USER_MANAGEMENT', 'statuses': []}, {'id': 'SERVICE_PARTNER', 'statuses': []}, {'id': 'WINDOW_HEATING', 'statuses': []}, {'id': 'ROUTE_IMPORT', 'statuses': []}, {'id': 'CHARGING', 'statuses': []}, {'id': 'AIR_CONDITIONING', 'statuses': []}, {'id': 'EXTENDED_CHARGING_SETTINGS', 'statuses': []}, {'id': 'VEHICLE_WAKE_UP_TRIGGER', 'statuses': []}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 203, in get_vehicle
    info = await self.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 159, in get_info
    return await self.rest_api.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 52, in get_info
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 32, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "capabilities" of type Capabilities in Info has invalid value {'capabilities': [{'id': 'AUTOMATION', 'statuses': []}, {'id': 'BATTERY_CHARGING_CARE', 'statuses': []}, {'id': 'BATTERY_SUPPORT', 'statuses': []}, {'id': 'CHARGING_PROFILES', 'statuses': []}, {'id': 'CHARGING_STATIONS', 'statuses': []}, {'id': 'DEALER_APPOINTMENT', 'statuses': ['INITIALLY_DISABLED']}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'MAP_UPDATE', 'statuses': []}, {'id': 'MEASUREMENTS', 'statuses': []}, {'id': 'PARKING_INFORMATION', 'statuses': []}, {'id': 'PARKING_POSITION', 'statuses': []}, {'id': 'PLUG_AND_CHARGE', 'statuses': []}, {'id': 'POI_SEARCH', 'statuses': []}, {'id': 'ROADSIDE_ASSISTANT', 'statuses': []}, {'id': 'ROUTING', 'statuses': []}, {'id': 'STATE', 'statuses': []}, {'id': 'TRAFFIC_INFORMATION', 'statuses': []}, {'id': 'VEHICLE_HEALTH_INSPECTION', 'statuses': []}, {'id': 'WARNING_LIGHTS', 'statuses': []}, {'id': 'WEB_RADIO', 'statuses': []}, {'id': 'AIR_CONDITIONING_TIMERS', 'statuses': []}, {'id': 'LOYALTY_PROGRAM', 'statuses': []}, {'id': 'AIR_CONDITIONING_SMART_SETTINGS', 'statuses': []}, {'id': 'POWERPASS_TARIFFS', 'statuses': []}, {'id': 'AIR_CONDITIONING_SAVE_AND_ACTIVATE', 'statuses': []}, {'id': 'CUBIC', 'statuses': []}, {'id': 'ROUTE_PLANNING_5_CHARGERS', 'statuses': []}, {'id': 'SUBSCRIPTIONS', 'statuses': []}, {'id': 'DESTINATIONS', 'statuses': []}, {'id': 'CHARGING_MEB', 'statuses': []}, {'id': 'VEHICLE_SERVICES_BACKUPS', 'statuses': []}, {'id': 'EV_ROUTE_PLANNING', 'statuses': []}, {'id': 'CHARGE_MODE_SELECTION', 'statuses': []}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'VEHICLE_HEALTH_WARNINGS', 'statuses': []}, {'id': 'PAY_TO_PARK', 'statuses': []}, {'id': 'ONLINE_SPEECH_GPS', 'statuses': []}, {'id': 'GUEST_USER_MANAGEMENT', 'statuses': []}, {'id': 'SERVICE_PARTNER', 'statuses': []}, {'id': 'WINDOW_HEATING', 'statuses': []}, {'id': 'ROUTE_IMPORT', 'statuses': []}, {'id': 'CHARGING', 'statuses': []}, {'id': 'AIR_CONDITIONING', 'statuses': []}, {'id': 'EXTENDED_CHARGING_SETTINGS', 'statuses': []}, {'id': 'VEHICLE_WAKE_UP_TRIGGER', 'statuses': []}]}
```
```

**Comment by WebSpider** [comment] 2024-09-26 07:27
Thank you for the error message. It contains car info weve never seen, which is the cause. 
We'll fix this and let you know its fixed by closing this issue

**Comment by TimMeadows** [comment] 2024-09-26 07:48
> Thank you for the error message. It contains car info weve never seen, which is the cause. We'll fix this and let you know its fixed by closing this issue

FAB - thank you. Let me know if you need any more information. 

Tim

**Closed** 2024-09-26 17:44 UTC
