### ISSUE TITLE
Failed Setup G-Tec engine

### ISSUE THREAD

**Issue by korttoma** [skodaconnect/homeassistant-myskoda#429] opened 2024-12-11 08:05 UTC
**Describe the bug**
Integration setup failing most likely due to the car being a G-Tec with special engine type and custom features

**Is this working in MySkoda app?***
Works fine in the MySkoda Android App

**Latest working release**
First time installing 1.14.2 after removing the depreciated Skoda Connect integration

**Debug logs**

[home-assistant_myskoda_2024-12-11T07-54-24.334Z.log](https://github.com/user-attachments/files/18091583/home-assistant_myskoda_2024-12-11T07-54-24.334Z.log)

**Installation:**
HassOS 

Core 2024.12.2
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.7

**Additional context**
Issue is most likely due to the car being a G-Tec (LNG/CNG Hybrid) with custom features compared to normal fuel car

**Comment by WebSpider** [comment] 2024-12-11 08:35
Yep. We'll fix this in next release.

There is a possibility that it will stumble on something else.

Please consider contributing the fixture of your car, so we can add it to our automated testsuite

**Comment by korttoma** [comment] 2024-12-11 08:41
> Yep. We'll fix this in next release.
> 
> There is a possibility that it will stumble on something else.
> 
> Please consider contributing the fixture of your car, so we can add it to our automated testsuite

Thanks for your fast response.

What is the fixture? And how can I contribute it?

**Comment by prvakt** [comment] 2024-12-11 09:31
Some small adjustments will be required because for hybrids we are expecting primary engine to be `gasoline` and secondary `electric`, but in this case primary is `cng` and secondary `gasoline`.. Probably it will cause only wrong sensor names..

Fixtures can be generated from myskoda integration, but I think we need to fix this missing cng engine type first otherwise integration will not start up.. I will have a look

**Comment by WebSpider** [comment] 2024-12-11 10:30
This is solved in `myskoda` version 0.15.0, and will be in the next release of the integration.

**Comment by prvakt** [comment] 2024-12-11 13:50
> Try out 1.15.1 and please report back to us 👍

if you can start integration without errors, please click on `DOWNLOAD DIAGNOSTICS` from device page. This will generate vehicle fixtures which we need in order to update primary/secondary range for CNG vehicles

**Comment by korttoma** [comment] 2024-12-12 06:07
Hi,
Unfortunately the integration is stil failing at Setup stage:

Logger: myskoda.rest_api
Source: /usr/local/lib/python3.13/site-packages/myskoda/rest_api.py:521
First occurred: 08:05:03 (1 occurrences)
Last logged: 08:05:03

Failed to deserialize data: {"overallMileageInKm":35,"overallTravelTimeInMin":53,"overallAverageMileageInKm":9,"overallAverageTravelTimeInMin":13,"overallAverageFuelConsumption":0.0,"overallAverageGasConsumption":4.37,"overallAverageSpeedInKmph":41,"vehicleType":"GAS","detailedStatistics":[{"date":"2024-12-09"},{"date":"2024-12-10"},{"date":"2024-12-11","tripIds":["3663033240","3665329542"],"mileageInKm":35,"travelTimeInMin":53,"averageFuelConsumption":0.0,"averageGasConsumption":4.37,"averageSpeedInKmph":41},{"date":"2024-12-12"},{"date":"2024-12-13"},{"date":"2024-12-14"},{"date":"2024-12-15"}]}
Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_json__
  File "/usr/local/lib/python3.13/enum.py", line 722, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 1189, in __new__
    raise ve_exc
ValueError: 'GAS' is not a valid VehicleType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 519, in _deserialize
    data = deserialize(text)
  File "<string>", line 12, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "vehicle_type" of type VehicleType in TripStatistics has invalid value 'GAS'

**Comment by WebSpider** [comment] 2024-12-12 07:29
Thanks for the report. You are the first reporting user of this type of car, so unfortunately this will be a bit of a hurdle run.

We'll be adding support for this and releasing a new version quickly.

If you feel up for it, you can see if you can install the library in skodaconnect/myskoda and try to run the gen-fixtures command. If not, no problem, we'll just take the hurdles as they come.

Thanks for your patience! 👍

**Comment by prvakt** [comment] 2024-12-12 07:30
fyi I'm already preparing update,

**Comment by korttoma** [comment] 2024-12-12 10:31
No worries, I fully understand that my car is special :D 
I will download the update as soon as it is available and give you an update if I can generate the fixture for you.

**Comment by WebSpider** [comment] 2024-12-12 14:15
We just released 1.15.2, feel free to try it out (after MySkoda app is working again)

**Comment by prvakt** [comment] 2024-12-12 22:04
> We just released 1.15.2, feel free to try it out (after MySkoda app is working again)

please test with `v1.15.3` ;)

**Comment by korttoma** [comment] 2024-12-13 05:30
Thank again for your effort on this, now the integration starts and here is the diagnostics:

[myskoda-01JETB6JX5WZW0WJWEP4VTSE2B-Škoda Octavia Combi-a2c053251f05845e0ecd895c9385f110.json](https://github.com/user-attachments/files/18121752/myskoda-01JETB6JX5WZW0WJWEP4VTSE2B-Skoda.Octavia.Combi-a2c053251f05845e0ecd895c9385f110.json)

**Comment by WebSpider** [comment] 2024-12-13 07:25
Awesome, we will add it to our regression tests and see what we can learn from the content 👍

**Comment by prvakt** [comment] 2024-12-13 07:33
There will be one more update comming in order to show remaining range for gas and combustion separatelly. Right know you probably have only range sensor combining these 2... 

In future we are planning to introduce also consumption sensors - may I know what unit is used for gas consumption? Is it kg/100km or l/100km ?

**Comment by korttoma** [comment] 2024-12-13 08:08
kg/100km is what I see in the car and in the app

**Comment by WebSpider** [comment] 2024-12-16 14:03
Closing this, followup will happen in mentioned issue. 
Thanks for making this known to us!

**Closed by WebSpider** 2024-12-16 14:03 UTC
Labels: bug, library
