### ISSUE TITLE
Integration fails at setup

### ISSUE THREAD

**Issue by Hount** [skodaconnect/homeassistant-myskoda#248] opened 2024-11-11 11:57 UTC
**Describe the bug**
When installing the integration to HA I don't see any entities, and integration page says:
No devices or entities
Failed setup, will retry: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

**Is this working in MySkoda app?***
Yes

**Latest working release**
I tested 1.8.1 and 1.8.2b1, neither works.

**Debug logs**
Not yet.

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version  ??
 - Python library versions ??
 - HA Core 2024.10.4
 - HA Supervisor 2024.10.3
 - Operating System 13.2
 - Frontend 20241002.4

**Additional context**
I am using MySkoda -app and previously I was using side-by-side MySkoda Essential -app.
Skoda-Connect integration works though.

**Comment by dvx76** [comment] 2024-11-11 12:04
Duplicate of https://github.com/skodaconnect/homeassistant-myskoda/issues/219, fixed in https://github.com/skodaconnect/myskoda/pull/176. Should be fixed in next release.

**Closed by dvx76** 2024-11-11 12:04 UTC
Labels: bug

**Comment by Hount** [comment] 2024-11-11 12:15
> Duplicate of #219, fixed in [skodaconnect/myskoda#176](https://github.com/skodaconnect/myskoda/pull/176). Should be fixed in next release.

Great! Sorry for duplicate. I promise I double checked to make sure there would not be an OPEN issue for the same bug. I learned to check also closed issues ;)

**Comment by WebSpider** [comment] 2024-11-11 12:18
Protip: Use the search-bar in the right upper corner and search for essential parts of the error ... this will also show closed issues, PR's, etc

**Comment by Hount** [comment] 2024-11-11 12:21
I feel I'm not alone - Given that this is already the second duplicate and third issue overall of the same bug. 
And most opensource projects I "collaborate" I feel the consensus is to close the issue when there is a release available.

**Comment by dvx76** [comment] 2024-11-11 12:48
It's a tradeoff. Open issues which already have a fix merged cause confusion too (for people reviewing/fixing the issues). Still I wouldn't mind closing issues on release bug Github auto-closes issues when the related PR merges. I don't know if it can be configured differently.
