### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by rsa-ingo** [skodaconnect/homeassistant-myskoda#439] opened 2024-12-11 21:38 UTC
This is just to help others that scratch their heads why suddedly the integration cannot authenticate anymore.
In my case this was not the fault of this integration. It worked fine but after a restart the integration could not authenticate to myskoda anymore.

This seems to be due to a updated data privacy statement that needs to be agreed to.

Solution: 

- In the MySkoda app log out and back in again. 
- Agree to the new privacy statement that is displayed
- In Home Assistant, reload the MySkoda integration

Just for completeness... HA debug logs will show:

WARNING (MainThread) [homeassistant.config_entries] Config entry 'YOUREMAILADDRESS' for myskoda integration could not authenticate
2024-12-11 22:07:39.660 ERROR (ImportExecutor_0) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 222, in _get_idk_session
    authentication = await self._enter_password(login_meta)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 167, in _enter_password
    location = response.headers["Location"]
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Location'

**Comment by ChristophCaina** [comment] 2024-12-12 05:32
hm...
My integration can't load... this was the same with the VW Connect integration - the strange thing here:
This night, my HA installation crashed for an unknown reason.
After this, I had also to relogin my AVM Fritz integration - as well, as the VW Connect integration could also not be loaded.

For the VW Integration, I could accept the terms and conditions, and everything was fine - but for Skoda....

... logged out from the (new) App, logged in again - no Terms & Conditions to accept.
But there's a different log in my case... it's more like a timeout:

```
Error setting up entry ***@***.de for myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/__init__.py", line 60, in async_setup_entry
    await myskoda.connect(config.data["email"], config.data["password"])
  File "/usr/local/lib/python3.13/site-packages/myskoda/myskoda.py", line 134, in connect
    await self.mqtt.connect(user.id, vehicles)
  File "/usr/local/lib/python3.13/site-packages/myskoda/mqtt.py", line 109, in connect
    await self._subscribed.wait()
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by domerich** [comment] 2024-12-12 06:36
Same here, the pending update was not notified to home assistant dash. After the update it worked again.

**Comment by Mehli12** [comment] 2024-12-12 07:35
Same here. The update for MySkoda was not announced in HA. After updating via HACS an HA restart all is fine.

**Comment by rsa-ingo** [comment] 2024-12-12 08:04
Just to clarify: for me the update to the MySkoda was announced in my HA dashboard. After updating the authentication error happened. 
After some fiddling around with debug logs I double checked the Android MySkoda app and did log out and back in again as I had a feeling that this could be a MySkoda issue in general.

That the update and the resulting reload causes the authentication issue (due to the privacy statement approval) makes sense as the session with MySkoda is reestablished. I suspect there is a long-lasting session with the MySokda backend and there isn't a dedicated authentiction happening for every call.

**Comment by Polster85** [comment] 2024-12-13 10:12
Same here, needed to logout and login again to the MySkoda app to accept a marketing/privacy question. After that a reload of the MySkoda integration fixed the issue.

**Comment by loetman** [comment] 2024-12-13 12:46
i had the same Problem. also an update to 1.15.3 take no effect. Then i logged of from my mobile and log in again. after that i become a question, that they will collect data from the app. i decline this. after that, it works again in HA.

**Comment by dvx76** [comment] 2024-12-14 21:13
Duplicate of #372

**Closed by dvx76** 2024-12-14 21:13 UTC
