### ISSUE TITLE
Auxiliary heater/ventilation and Inspection days not working - Skoda Kodiaq 2023 L&K

### ISSUE THREAD

**Issue by skuduu** [skodaconnect/homeassistant-myskoda#406] opened 2024-12-04 16:44 UTC
**Describe the bug**
Problem 1: Auxiliary heater shows "Unknown" in HA and there is no option for ventilation. Both heating and ventilation are visible and functioning in MySkoda app. I've tried restarting HA and removing MySkoda integration and starting from scratch.

Problem 2: The Next inspection in days and Oil service in days is showing wrong numbers. It is showing 13344:00:00 and it should be 556 days.

![Screenshot_20241204_175407_io_homeassistant_companion_android_WebViewActivity2](https://github.com/user-attachments/assets/6e86ef39-3900-40bb-910d-9e09cb599c70)

![Screenshot_20241204_175417_io_homeassistant_companion_android_WebViewActivity](https://github.com/user-attachments/assets/bc3db60d-1032-4315-aacb-d45c333ac9fe)

![Screenshot_20241204_175458_io_homeassistant_companion_android_WebViewActivity](https://github.com/user-attachments/assets/4b3efb6c-d226-4294-bbc3-3937f84065a3)

**Is this working in MySkoda app?***
Yes, everything is working in MySkoda app

**Latest working release**
None

**Debug logs**
I have no idea what to copy/paste from the logs, maybe someone can guide me if it is necessary. I did the Press and get Fixtures -thing, included below.
[Fixtures-Skoda_Kodiaq_2023_LK.txt](https://github.com/user-attachments/files/18011404/Fixtures-Skoda_Kodiaq_2023_LK.txt)

**Installation:**
 - Hass OS 14.0
 - MySkoda integration 1.14.1
 
**Additional context**
Happy to provide more info if someone tells me what i should be looking for/doing :)

**Comment by prvakt** [comment] 2024-12-04 16:58
please update to latest MySkoda.. or you just forgot to restart HA after update?
AuxiliaryHeater has been fixed in 1.14.0 but looks like you are running the 1.13.1 as I can see from fixtures because MySkoda lib in fixtures is 0.13.4

**Comment by prvakt** [comment] 2024-12-04 17:02
and problem with Next Inspection and Oil Service is caused by the bug in the Home Assistant frontend.. 

https://github.com/home-assistant/frontend/issues/21967#issuecomment-2348814738

As soon as it's fixed in frontend, it will work for us as well...

**Comment by skuduu** [comment] 2024-12-04 17:18
Thanks for the info on the version! In HACS it showed that i had the correct version but when I looked in HA-Settings-Devices-MySkoda it actually showed 1.31.1 so i deleted the integration completely and also removed leftover folder in custom_components folder and now i have the correct version!

The auxiliary heater is now showing data, have not yet tried turning heater on/off but all seems to be good!

This "bug" turned out to be a bug in my own head and a complete waste of everyones time :) Big Thanks to you and everyone else who keep this project running!

**Comment by prvakt** [comment] 2024-12-04 17:23
@skuduu: no problem, we are all humans :) please check your auxiliary heater functionality and if everything is OK, dont forget to close this issue ;)

**Closed** 2024-12-04 17:27 UTC
Labels: bug
