### ISSUE TITLE
Unavailable entities

### ISSUE THREAD

**Issue by SenadM** [skodaconnect/homeassistant-myskoda#144] opened 2024-10-28 20:45 UTC
Have the latest HA and MySkoda Integration 1.6.2

since I updated to 1.6.0 entities are becoming unavailable in HA a couple of times a day. I either have to restart HA or reload the integration for it to work again.

**Comment by WebSpider** [comment] 2024-10-28 21:03
Can you check your logging if you see anything resembling #140?

**Comment by dvx76** [comment] 2024-10-30 07:47
It's great to report issues in Gitlab, thank you, but please include additional detail and preferably (debug) logs. Just saying it doesn't work leaves us guessing what the problem is, at best.

This is most likely a dup of #140 indeed and will hopefully be fixed in the next release indeed.

**Comment by WebSpider** [comment] 2024-10-30 09:33
Version 1.6.4 has just been released that should fix this. Please update at your earliest convenience and let us know if you are still seeing this.

**Comment by mbrackjr** [comment] 2024-10-30 17:15
Experienced same unavailablity of entities and instability of HA overall with earlier releases.  Upgraded around 6 hours ago and so far so good; no issues yet, so looks very promising. 
Thanks a LOT for diligently getting myskoda supported!

**Closed** 2024-10-30 20:07 UTC
Labels: bug, duplicate
